# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/intelFPGA_lite/16.1/modelsim_ase/win32aloem
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/git/v_axis_gen/v_axis_gen.cache/wt [current_project]
set_property parent.project_path D:/FPGA/git/v_axis_gen/v_axis_gen.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/FPGA/git/v_axis_gen/v_axis_gen.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/imports/axis-test/axisviout2vga.vhd
  D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/imports/axis-test/resetgen.vhd
  D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/imports/axis-test/test_pattern_gen.vhd
  D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/imports/axis-test/v_axis_gen.vhd
}
read_ip -quiet D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc]

read_ip -quiet D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/constrs_1/imports/v_axis_gen/arty.xdc
set_property used_in_implementation false [get_files D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/constrs_1/imports/v_axis_gen/arty.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top v_axis_gen -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef v_axis_gen.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file v_axis_gen_utilization_synth.rpt -pb v_axis_gen_utilization_synth.pb"
