# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0.xci
# IP: The module: 'v_axi4s_vid_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_axi4s_vid_out_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_axi4s_vid_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0.xci
# IP: The module: 'v_axi4s_vid_out_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_axi4s_vid_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/git/v_axis_gen/v_axis_gen.srcs/sources_1/ip/v_axi4s_vid_out_0/v_axi4s_vid_out_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'v_axi4s_vid_out_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
